apiVersion: v1
kind: Service
metadata:
  name: dandelion-grass-classifier-service
  labels:
    app: dandelion-grass-classifier
spec:
  type: NodePort
  selector:
    app: dandelion-grass-classifier
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30080
      protocol: TCP
      name: http
